// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFCAccessSystem.Data;

#nullable disable

namespace NFCAccessSystem.Migrations
{
    [DbContext(typeof(AccessSystemContext))]
    [Migration("20220606062529_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("NFCAccessSystem.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Admin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Authorized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OfflineAuth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TotpSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("TagUid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NFCAccessSystem.Models.ErrorViewModel", b =>
                {
                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.ToTable("ErrorViewModel");
                });
#pragma warning restore 612, 618
        }
    }
}
